#!/bin/sh -e
# CPU count + freq monitor for Odroid XU3/4 (big cores) and N1 (big cores)

. /usr/lib/byobu/include/shutil
read freq < /sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq;
freq=`echo $freq/1000000 | bc -l`

cpus=0;
for i in `cat /sys/devices/system/cpu/cpu4/cpufreq/affected_cpus`; do
        read current < /sys/devices/system/cpu/cpu${i}/online
        cpus=$(($current+$cpus));
done
[ "$cpus" -ne "0" ] || return
[ -n "$freq" ] || return
color b m W; printf "%dx%.1f" "$cpus" "$freq"; color -;color m W; printf "%s" "GHz"; color -- 
printf "\n"
# vi: syntax=sh ts=4 noexpandtab
