#!/bin/sh -e
# CPU count + freq monitor for Odroid XU3/4 (little cores) or N1 (little cores)
. /usr/lib/byobu/include/shutil
read freq < /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq;
freq=`echo $freq/1000000 | bc -l`

cpus=0;
for i in `cat /sys/devices/system/cpu/cpu0/cpufreq/affected_cpus`; do
	read current < /sys/devices/system/cpu/cpu${i}/online
	cpus=$(($current+$cpus));
done

[ "$cpus" -ne "0" ] || return
[ -n "$freq" ] || return
color b c W; printf "%dx%.1f" "$cpus" "$freq"; color -;color c W; printf "%s" "GHz"; color -- 
printf "\n"
# vi: syntax=sh ts=4 noexpandtab
